-- MySQL Script generated by MySQL Workbench
-- Tue May 11 17:13:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Internet_provider
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Internet_provider
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Internet` DEFAULT CHARACTER SET utf8 ;
